# Generated by Django 2.2 on 2019-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200, null=True)),
                ('paper_title', models.CharField(max_length=200, null=True)),
                ('conference', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'publication',
            },
        ),
    ]
