# Generated by Django 2.2 on 2019-11-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfacemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Democard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50, null=True, verbose_name='项目名称')),
                ('project_ico', models.CharField(max_length=80, null=True, verbose_name='图标链接')),
                ('project_description', models.CharField(max_length=200, null=True, verbose_name='项目介绍')),
                ('url_outer', models.CharField(max_length=50, null=True, verbose_name='外网入口')),
                ('url_intranet', models.CharField(max_length=50, null=True, verbose_name='内网入口')),
            ],
            options={
                'verbose_name': 'Democard',
                'verbose_name_plural': 'Democard',
                'db_table': 'zx_democard',
            },
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publications', 'verbose_name_plural': 'publications'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conference',
            field=models.CharField(max_length=50, null=True, verbose_name='会议/期刊'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paper_title',
            field=models.CharField(max_length=200, null=True, verbose_name='论文名称'),
        ),
    ]
